SCR_JournalSetupConfig {
 m_aJournals {
  SCR_JournalConfig "{65BCD15059CF9310}" {
   m_FactionKey "ARGA"
   m_aEntries {
    SCR_JournalEntry "{65BCD1526F2C444E}" {
     m_eJournalEntryType Custom
     m_sCustomEntryName "Información"
     m_sEntryText "Nombre de la misión: Operación Sangre Negra"\
     "Editor: Mateo"\
     "Carácter: Misión Reforger"\
     "Horario in game: 0000"\
     "Fecha: 19/07/2017"\
     "Clima: Despejado"\
     "Ubicación: Takistan (Reforger)"
    }
    SCR_JournalEntry "{65BCD15059CF93F9}" {
     m_eJournalEntryType Custom
     m_sCustomEntryName "Situación Histórica"
     m_sEntryText "Desde hace décadas, la región de Takistan ha sido escenario de conflictos internos y luchas por el control territorial. El antiguo bunker militar se encontraba abandonado tras la retirada del ejército estadounidense, pero en los últimos meses ha sido tomado por fuerzas insurgentes del Medio Oriente, convirtiéndose en un bastión para sus operaciones en la zona."
    }
    SCR_JournalEntry "{65BCD15059CF93F4}" {
     m_eJournalEntryType Custom
     m_sCustomEntryName "Situación"
     m_sEntryText "La amenaza insurgente representa un peligro inminente para la estabilidad regional y las operaciones de nuestros clientes. Se ha ordenado el despliegue de las fuerzas ArgA para neutralizar la presencia enemiga y destruir lo que queda de las instalaciones estadounidenses."
    }
    SCR_JournalEntry "{65BCD15059CF93F2}" {
     m_eJournalEntryType Custom
     m_sCustomEntryName "Extracto de inteligencia"
     m_sEntryText "Escuadrones de insurgentes equipados con armamento ligero y pesado defienden el bunker y sus alrededores. Se reportan armamentos y un generador dentro de las instalaciones del bunker. No sabemos si saben de nuestra presencia pero contamos con equipos de vision nocturna que nos dara una ventaja."
    }
    SCR_JournalEntry "{65BCD153FD7CB694}" {
     m_eJournalEntryType Custom
     m_sCustomEntryName "Objetivos"
     m_sEntryText "1. Infiltrar y asegurar el perímetro del antiguo bunker estadounidense ubicado en el aeropuerto de Rasman."\
     "2. Neutralizar todas las fuerzas insurgentes presentes."\
     "3. Destruir el bunker estadounidense y disfrutar de los fuegos artificiales."\
     ""
    }
    SCR_JournalEntry "{65BCD153FD022895}" {
     m_eJournalEntryType Custom
     m_sCustomEntryName "Fuerzas Enemigas"
     m_sEntryText "- Fuerzas insurgentes armados con equipamiento armamento Sovietico"\
     "- Posibles refuerzos motorizados"\
     ""
    }
    SCR_JournalEntry "{65BCD153FDA28BCF}" {
     m_eJournalEntryType Custom
     m_sCustomEntryName "Nuestros Recursos"
     m_sEntryText "Disponemos de:"\
     "- Pelotón de infantería motorizada"\
     "- Vehículos blindados ligeros para el avance"\
     "- Sistemas de visión nocturna"\
     ""
    }
    SCR_JournalEntry "{65BCD15CD0CD50B0}" {
     m_eJournalEntryType Custom
     m_sCustomEntryName "Editores"
     m_sEntryText "|ArgA|Mateo"
    }
   }
  }
 }
}