SCR_MissionHeader {
 World "{CA42157C5FA8F3CC}worlds/sangrenegraworld.ent"
 m_sName "OP. Sangre Negra"
 m_sAuthor "|ArgA|Mateo"
 m_sIcon "{4AB06C202767800A}UI/Images/OPSangreNergra_TY.edds"
 m_sLoadingScreen "{4AB06C202767800A}UI/Images/OPSangreNergra_TY.edds"
 m_sPreviewImage "{4AB06C202767800A}UI/Images/OPSangreNergra_TY.edds"
 m_sGameMode "Mission"
 m_iPlayerCount 64
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_iStartingHours 0
 m_fXpMultiplier 0
 m_ACE_Settings ACE_MissionHeaderSettings "{65C30B5398F16263}" {
  m_ACE_Finger_Settings ACE_Finger_Settings "{65C30B53997F3DF9}" {
   m_bCanPingAttach 0
   m_fPingRangeM 0
  }
  m_ACE_Medical_Settings ACE_Medical_Settings "{65C30B539E10BF17}" {
   m_fSecondChanceRegenScale 0.025
   m_bSecondChanceOnHeadEnabled 1
   m_bHealSupplyUsageEnabled 0
   m_fMedicalKitMaxHealScaled 1
  }
 }
}